TRIES

diff --git a/buildtagpush b/buildtagpush
--- a/buildtagpush
+++ b/buildtagpush
@@ -33,6 +33,7 @@ export CACHE_TAG=${CACHE_TAG:-$TAG}
 export WORKDIR=${WORKDIR:-/workspace}
 export DOCKERFILE=${DOCKERFILE:-Dockerfile}
 export BUILD_OPTS=${BUILD_OPTS:-}
+export TRIES=${TRIES:-6}
 
 cd "$WORKDIR"
 
@@ -69,17 +70,20 @@ wait $(jobs -p)
 _output "BUILD $REGISTRY/$IMAGE:$TAG with cache from $REGISTRY/$IMAGE:$CACHE_TAG"
 
 (
-  for try in {1..2}; do
+  for try in {1..$TRIES}; do
     # NOTE: $BUILD_OPTS needs to be without quotes to expand properly
     if docker build -f "$DOCKERFILE" --cache-from="$REGISTRY/$IMAGE:$CACHE_TAG" --build-arg BUILDKIT_INLINE_CACHE=1 -t "$REGISTRY/$IMAGE:$TAG" $BUILD_OPTS .; then
       break
     else
-      if [ "$try" != "1" ]; then
-        echo "second attempt failed, exit 1"
+      if [ "$try" = "$TRIES" ]; then
+        echo "last attempt failed, exit 1"
         exit 1
+      else
+        echo "$try attempt failed, sleep $try"
+        sleep "$try"
       fi
 
-      echo "first attempt failed, trying to pull deps"
+      echo "trying to pull deps"
       # https://github.com/moby/moby/issues/40262#issuecomment-656036657)
       from_images=""
       copy_froms=""
